### ISSUE TITLE
Temperature Sensor for Main_ECU

### ISSUE THREAD

**Issue by karvindass** [hytech-racing/code-2017#2]
Code that is supposed to read in temperature for the Main_ECU is not working correctly. Room temperature is not being shown, and warming up the thermistor is resulting in the sensor reading for temperature decreasing

```c++
thermValue = analogRead(THERMISTOR_PIN);
    //compute actual temperature with math
    float resistance = ((float) 1023 / (float) thermValue) - 1;
    resistance = SERIESRESISTOR / resistance;
    Serial.println(resistance);
    thermTemp = resistance / THERMISTORNOMINAL;
    thermTemp = log(thermTemp);
    thermTemp /= BCONSTANT;
    thermTemp += 1.0 / (TEMPERATURENOMINAL + 273.15);
    thermTemp = 1.0 / thermTemp;
    thermTemp -= 273.15;
```

**Comment by nathancheek** [comment]
What are your values for SERIESRESISTOR, THERMISTORNOMINAL, BCONSTANT, and TEMPERATURENOMINAL?

**Comment by karvindass** [comment]
```c++
const int SERIESRESISTOR = 10000;
const int THERMISTORNOMINAL = 10000;
const int BCONSTANT = 3900;
const int TEMPERATURENOMINAL = 25;
```

**Comment by nathancheek** [comment]
The value returned by analogRead() corresponds to 0V-3.3V. The thermistor is part of a resistor divider connected to 5V.

(5 * SERIESRESISTOR) / (resistance + SERIESRESISTOR) = voltageIn
(3.3 * thermValue) / 1023 = voltageIn

Solve for resistance.

Try:
`float resistance = (5 * SERIESRESISTOR * 1023) / (3.3 * thermValue) - SERIESRESISTOR`
or to simplify:
`float resistance = 1550 * SERIESRESISTOR / thermValue - SERIESRESISTOR`
